# Generated by Django 3.0.5 on 2020-04-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField(unique=True)),
                ('user_id', models.IntegerField()),
                ('vehicle_model_id', models.IntegerField()),
                ('package_id', models.FloatField(blank=True, null=True)),
                ('travel_type_id', models.IntegerField()),
                ('from_area_id', models.FloatField(blank=True, null=True)),
                ('to_area_id', models.FloatField(blank=True, null=True)),
                ('from_city_id', models.FloatField(blank=True, null=True)),
                ('to_city_id', models.FloatField(blank=True, null=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('online_booking', models.IntegerField()),
                ('mobile_site_booking', models.IntegerField()),
                ('booking_created', models.DateTimeField()),
                ('from_lat', models.FloatField(blank=True, null=True)),
                ('from_long', models.FloatField(blank=True, null=True)),
                ('to_lat', models.FloatField(blank=True, null=True)),
                ('to_from_long', models.FloatField(blank=True, null=True)),
                ('Car_Cancellation', models.IntegerField()),
            ],
        ),
    ]
